# Generated by Django 5.2.12 on 2026-04-27 04:27

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserThemePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_clr', models.CharField(default='#f8f9ff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('line_clr', models.CharField(default='#42434a', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('hover_clr', models.CharField(default='#eef2ff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('text_clr', models.CharField(default='#ffffff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('accent_clr', models.CharField(default='#59e7ec', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_text_clr', models.CharField(default='#111827', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('container_background_base', models.CharField(default='#f3f0fe', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('secondary_base_clr', models.CharField(default='#ce9aff', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('sidebar_gradient_start', models.CharField(default='#8b5cf6', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('sidebar_gradient_end', models.CharField(default='#60a5fa', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('profile_icon_emoji', models.CharField(blank=True, max_length=16)),
                ('agenda_icon_emoji', models.CharField(blank=True, max_length=16)),
                ('default_activity_icon_emoji', models.CharField(blank=True, max_length=16)),
                ('profile_icon_image', models.ImageField(blank=True, null=True, upload_to='ui_icons/profile/')),
                ('agenda_icon_image', models.ImageField(blank=True, null=True, upload_to='ui_icons/agenda/')),
                ('default_activity_icon_image', models.ImageField(blank=True, null=True, upload_to='ui_icons/activity_default/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='theme_preference', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
