# Generated by Django 5.2.12 on 2026-04-08 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planify', '0002_alter_user_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
