# Generated by Django 6.0.4 on 2026-04-15 12:19

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#6366f1', max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('kind', models.CharField(choices=[('event', 'Evento'), ('task', 'Tarefa')], max_length=10)),
                ('activity_type', models.CharField(choices=[('class', 'Aula'), ('exam', 'Prova'), ('assignment', 'Trabalho'), ('study', 'Estudo'), ('meeting', 'Reunião'), ('presentation', 'Apresentação'), ('personal', 'Pessoal')], max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(code='invalid_color', message='A cor deve ser um código hexadecimal válido (ex: #FF0000).', regex='^#[0-9A-Fa-f]{6}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='schedules.schedule')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checked_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to='schedules.activity')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('activity', 'user')},
            },
        ),
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Administrador'), ('member', 'Participante')], default='member', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to=settings.AUTH_USER_MODEL)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='schedules.schedule')),
            ],
            options={
                'unique_together': {('schedule', 'user')},
            },
        ),
    ]
