# Generated by Django 6.0.3 on 2026-04-26 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_schedule_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='priority',
            field=models.CharField(choices=[('urgent_important', 'Urgente e importante'), ('urgent', 'Urgente'), ('important', 'Importante'), ('not_urgent_not_important', 'Não urgente e nem importante')], default='important', max_length=40),
        ),
    ]
