# Generated by Django 5.2.12 on 2026-04-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0003_activity_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='activity',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_icons/'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='icon_emoji',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='schedule',
            name='icon_image',
            field=models.ImageField(blank=True, null=True, upload_to='schedule_icons/'),
        ),
    ]
