# Generated by Django 5.2.12 on 2026-04-29 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0005_update_schedule_default_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='activity_type_colors',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
