# Generated by ChatGPT on 2026-05-03

from django.db import migrations, models
import schedules.models


DEFAULT_ACTIVITY_TYPE_COLORS = {
    "class": "#3b82f6",
    "exam": "#ef4444",
    "assignment": "#f59e0b",
    "study": "#7c3aed",
    "meeting": "#06b6d4",
    "presentation": "#4f46e5",
    "personal": "#14b8a6",
}


def backfill_activity_type_colors(apps, schema_editor):
    Schedule = apps.get_model("schedules", "Schedule")

    for schedule in Schedule.objects.all().iterator():
        current = schedule.activity_type_colors or {}
        merged = {**DEFAULT_ACTIVITY_TYPE_COLORS, **current}

        if merged != current:
            schedule.activity_type_colors = merged
            schedule.save(update_fields=["activity_type_colors"])


class Migration(migrations.Migration):

    dependencies = [
        ("schedules", "0006_schedule_activity_type_colors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schedule",
            name="activity_type_colors",
            field=models.JSONField(blank=True, default=schedules.models.default_activity_type_colors),
        ),
        migrations.RunPython(backfill_activity_type_colors, migrations.RunPython.noop),
    ]
